-- -- 코드를 입력하세요
WITH SUB AS(
SELECT A.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE*BA.SALES) TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES BA ON B.BOOK_ID = BA.BOOK_ID
WHERE
    TO_CHAR(BA.SALES_DATE,'YYYY-MM')='2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, SUB.CATEGORY, SUB.TOTAL_SALES
FROM AUTHOR A
    JOIN SUB ON A.AUTHOR_ID = SUB.AUTHOR_ID
ORDER BY A.AUTHOR_ID, SUB.CATEGORY DESC
    ;
