-- -- 코드를 입력하세요
WITH SUB AS(
SELECT A.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE*BA.SALES) TOTAL_SALES
FROM BOOK B,
    AUTHOR A,
    BOOK_SALES BA
WHERE 1=1
    AND B.AUTHOR_ID=A.AUTHOR_ID
    AND B.BOOK_ID=BA.BOOK_ID
    AND TO_CHAR(BA.SALES_DATE,'YYYY-MM')='2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, SUB.CATEGORY, SUB.TOTAL_SALES
FROM AUTHOR A, SUB
WHERE A.AUTHOR_ID=SUB.AUTHOR_ID
ORDER BY A.AUTHOR_ID, SUB.CATEGORY DESC
    ;
    
    
