WITH SEC_GEN AS (
    SELECT ED1.ID
    FROM
        ECOLI_DATA ED1
    JOIN
        ECOLI_DATA ED2
    ON 
        ED1.PARENT_ID = ED2.ID
    WHERE ED2.PARENT_ID IS NULL)

SELECT  
    ED.ID
FROM
    SEC_GEN
JOIN 
    ECOLI_DATA ED
ON 
    SEC_GEN.ID = ED.PARENT_ID
ORDER BY ED.ID;
