SELECT ID, COALESCE(SUB.CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (SELECT PARENT_ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) SUB
ON E.ID = SUB.PARENT_ID
ORDER BY ID ASC;