
SELECT ID,
    CASE
    WHEN 
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)
        <= (SELECT COUNT(SIZE_OF_COLONY)
            FROM ECOLI_DATA)/4
    THEN 'CRITICAL'
    WHEN
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)
        <= (SELECT COUNT(SIZE_OF_COLONY)
            FROM ECOLI_DATA)/4*2
    THEN 'HIGH'
    WHEN
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)
        <= (SELECT COUNT(SIZE_OF_COLONY)
            FROM ECOLI_DATA)/4*3
    THEN 'MEDIUM'
    WHEN
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)
        <= (SELECT COUNT(SIZE_OF_COLONY)
            FROM ECOLI_DATA)
    THEN 'LOW'
    END COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID
