-- 코드를 입력하세요
WITH HEAVY_USER AS(
    SELECT host_id
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2)

SELECT *
FROM PLACES
WHERE HOST_ID IN (
    SELECT host_id
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2)
ORDER BY ID;