-- -- -- 코드를 입력하세요
-- -- -- '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액을 구해
-- -- -- 대여 기록 ID와 대여 금액 리스트를 출력
-- -- -- 대여 금액 기준 내림차순, 대여 기록 ID 내림차순
SELECT H.HISTORY_ID, C.DAILY_FEE*(H.END_DATE-H.START_DATE+1) FEE
        FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE C.CAR_ID = H.CAR_ID
            AND C.CAR_TYPE = '트럭'
            AND H.END_DATE-H.START_DATE+1 < 7
            
UNION

SELECT SUB.HISTORY_ID, 
    CASE 
        WHEN P.DURATION_TYPE='7일 이상' THEN SUB.FEE * (1- P.DISCOUNT_RATE / 100.0)
    END FEE
FROM 
        (SELECT H.HISTORY_ID, C.CAR_TYPE, H.END_DATE-H.START_DATE+1 DAYS, 
         C.DAILY_FEE*(H.END_DATE-H.START_DATE+1) FEE
        FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE C.CAR_ID = H.CAR_ID
            AND C.CAR_TYPE = '트럭'
            AND H.END_DATE-H.START_DATE+1 BETWEEN 7 AND 29) SUB,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE P.DURATION_TYPE = '7일 이상'
AND P.CAR_TYPE='트럭'

UNION

SELECT SUB.HISTORY_ID, 
    CASE 
        WHEN P.DURATION_TYPE='30일 이상' THEN SUB.FEE*(1- P.DISCOUNT_RATE / 100.0)
    END FEE
FROM 
        (SELECT H.HISTORY_ID, C.CAR_TYPE, H.END_DATE-H.START_DATE+1 DAYS, 
         C.DAILY_FEE*(H.END_DATE-H.START_DATE+1) FEE
        FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE C.CAR_ID = H.CAR_ID
            AND C.CAR_TYPE = '트럭'
            AND H.END_DATE-H.START_DATE+1 BETWEEN 30 AND 89) SUB,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE P.DURATION_TYPE = '30일 이상'
AND P.CAR_TYPE='트럭'

UNION

SELECT SUB.HISTORY_ID, 
    CASE 
        WHEN P.DURATION_TYPE='90일 이상' THEN SUB.FEE*(1- P.DISCOUNT_RATE / 100.0)
    END FEE
FROM 
        (SELECT H.HISTORY_ID, C.CAR_TYPE, H.END_DATE-H.START_DATE+1 DAYS, 
         C.DAILY_FEE*(H.END_DATE-H.START_DATE+1) FEE
        FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE C.CAR_ID = H.CAR_ID
            AND C.CAR_TYPE = '트럭'
            AND H.END_DATE-H.START_DATE+1 >= 90) SUB,
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE P.DURATION_TYPE = '90일 이상'
AND P.CAR_TYPE='트럭'

ORDER BY FEE DESC, HISTORY_ID DESC;

