WITH RENTAL_DAYS AS (
    SELECT 
        H.HISTORY_ID, 
        H.CAR_ID, 
        (H.END_DATE - H.START_DATE + 1) AS DAYS
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN 
        CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE 
        C.CAR_TYPE = '트럭'
),
RENTAL_COST AS (
    SELECT 
        R.HISTORY_ID, 
        R.DAYS, 
        C.DAILY_FEE,
        C.DAILY_FEE * R.DAYS AS TOTAL_COST
    FROM 
        RENTAL_DAYS R
    JOIN 
        CAR_RENTAL_COMPANY_CAR C ON R.CAR_ID = C.CAR_ID
),
DISCOUNT_APPLIED AS (
    SELECT 
        RC.HISTORY_ID, 
        RC.TOTAL_COST,
        CASE
            WHEN RC.DAYS >= 90 THEN RC.TOTAL_COST * (1 - DP.DISCOUNT_RATE / 100.0)
            WHEN RC.DAYS >= 30 THEN RC.TOTAL_COST * (1 - DP.DISCOUNT_RATE / 100.0)
            WHEN RC.DAYS >= 7 THEN RC.TOTAL_COST * (1 - DP.DISCOUNT_RATE / 100.0)
            ELSE RC.TOTAL_COST
        END AS DISCOUNTED_COST
    FROM 
        RENTAL_COST RC
    LEFT JOIN 
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
        ON DP.CAR_TYPE = '트럭' AND (
            (DP.DURATION_TYPE = '90일 이상' AND RC.DAYS >= 90) OR 
            (DP.DURATION_TYPE = '30일 이상' AND RC.DAYS >= 30 AND RC.DAYS < 90) OR
            (DP.DURATION_TYPE = '7일 이상' AND RC.DAYS >= 7 AND RC.DAYS < 30)
        )
)
SELECT 
    HISTORY_ID, 
    CAST(DISCOUNTED_COST AS INTEGER) AS FEE
FROM 
    DISCOUNT_APPLIED
ORDER BY 
    FEE DESC, 
    HISTORY_ID DESC;
