WITH SUB AS(
    SELECT IT1.ITEM_ID PAR, IT2.ITEM_ID CHI
    FROM 
        ITEM_TREE IT1
    JOIN
        ITEM_TREE IT2
    ON
        IT1.ITEM_ID = IT2.PARENT_ITEM_ID),
SUB2 AS(
    SELECT CHI
    FROM ITEM_INFO II
    JOIN SUB
    ON II.ITEM_ID = SUB.PAR
    WHERE II.RARITY = 'RARE')

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT * FROM SUB2)
ORDER BY ITEM_ID DESC;