SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM    (SELECT FISH_TYPE,
        CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH END LENGTH,
        TIME
        FROM FISH_INFO) SUB
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE
;